---
title: "ST558 Project 1"
author: "Mu-Tien, Lee"
date: "2020,09.04"
output:
  github_document:
      toc: true
---

```{r setup, include=FALSE, linewidth=60}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)

```

## Require Package
```{r require package}
#install.packages("qwraps2")
library(rmarkdown)
library(dplyr)
library(tidyverse)
library(RSQLite)
library(bigrquery)
library(httr)
library(jsonlite)
library(ggplot2)
library(qwraps2)
```


## Data cleaning
### Building functions to reach statsAPI
```{r reaching statsAPI}
statsAPI <- function(x,teamid=NULL,year=NULL, ...){
#setting up base url for stats API
base_url <-"https://statsapi.web.nhl.com/api/v1/teams"
modifiers <- x

#construct the full path
if (is.null(teamid)){
full_url <- paste0(base_url, "?", modifiers)
}
else {
  full_url <- paste0(base_url, "/", teamid, "?", modifiers)
  } 

# retrieve information in raw form
GET(full_url)
#transfer into JSON text form
text <- content(GET(full_url),"text")
#convert it to a list
mydata <- fromJSON(text, flatten = TRUE) 
mydata<- as.data.frame(mydata)
return(mydata)
}

m<- statsAPI("expand=team.roster")
n<- statsAPI("expand=person.names")
o<- statsAPI("expand=team.schedule.next")
p<- statsAPI("expand=team.schedule.previous")
q<- statsAPI("expand=team.stats")
r<- statsAPI("expand=team.roster&season=20142015")
s<- statsAPI("teamId=4,5,29")
t<- statsAPI("stats=statsSingleSeasonPlayoffs")

```

### Building functions to reach recordAPI
```{r reaching recordAPI}
recordAPI <- function(x,teamid=NULL,...){
#setting up base url for stats API
base_url <-"https://records.nhl.com/site/api"
modifiers <- x

if (is.null(teamid)){
    full_url <- paste0(base_url, "/", modifiers)
  }
else if (x %in% c("franchise","franchise-team-totals")) {
    stop("Sorry,table franchise and franchise-team-totals cannot indicate team")
  }
else {
  full_url <- paste0(base_url, "/", modifiers,"?cayenneExp=franchiseId=", teamid)
  } 

# retrieve information in raw form
GET(full_url)
#transfer into JSON text form
text <- content(GET(full_url),"text")
#convert it to a list
mydata <- fromJSON(text, flatten = TRUE) 
mydata<- as.data.frame(mydata)
return(mydata)
}

a<-recordAPI("franchise")
b<-recordAPI("franchise-team-totals")
c<-recordAPI("franchise-season-records",1)
d<-recordAPI("franchise-goalie-records",1)
e<-recordAPI("franchise-skater-records",1)
```

### accessory for API endpoints
```{r accessory for endpoints}
endpoints <- function(x, teamid=NULL, year=NULL, ...){
  record <- c("franchise","franchise-team-totals","franchise-season-records", "franchise-goalie-records", "franchise-skater-records")
  stats <- c()
  if (x %in% record) recordAPI(x,teamid,...)
  else if (x %in% stats) statsAPI(x, teamid)
  else stop("Please enter the correct name of your enpoints")
}
try<-endpoints("franchise-season-records",1)
```

## Data analysis

```{r}
montreal <-recordAPI("franchise-season-records",8)
tornonto <-recordAPI("franchise-season-records",10)
detroit <-recordAPI("franchise-season-records",17)
carolinas <-recordAPI("franchise-season-records",12)
seasonrecord <- rbind.data.frame(Motreal_Canadiens=montreal, Tornonto_MapleLeafs=tornonto, Detroit_RedWings=detroit, Carolinas_Hurricanes=carolinas)
seasonrecord

montreal <-recordAPI("franchise-goalie-records",8)
tornonto <-recordAPI("franchise-goalie-records",10)
detroit <-recordAPI("franchise-goalie-records",17)
carolinas <-recordAPI("franchise-goalie-records",12)
goalierecord <- rbind.data.frame(Motreal_Canadiens=montreal, Tornonto_MapleLeafs=tornonto, Detroit_RedWings=detroit, Carolinas_Hurricanes=carolinas)

montreal <-recordAPI("franchise-skater-records",8)
tornonto <-recordAPI("franchise-skater-records",10)
detroit <-recordAPI("franchise-skater-records",17)
carolinas <-recordAPI("franchise-skater-records",12)
skaterrecord <- rbind.data.frame(Motreal_Canadiens=montreal, Tornonto_MapleLeafs=tornonto, Detroit_RedWings=detroit, Carolinas_Hurricanes=carolinas)

mydata <- statsAPI("teamId=8,10,17,12")



bar1 <- ggplot(data=new,aes(x=data.gamesPlayed))
bar1+geom_histogram(aes(fill=teams.division.name),binwidth = 500, position= "dodge")

```

```{r build my data}
teamtotal<-recordAPI("franchise-team-totals")%>% filter(is.na(data.lastSeasonId))
division <- statsAPI("expand=team.roster")%>% select(teams.id, teams.division.name, teams.division.nameShort, teams.conference.name) %>%rename(data.teamId=teams.id)

new <- left_join(teamtotal,division, by="data.teamId") %>% mutate(winrate=data.wins/data.gamesPlayed, winlossrate=data.wins/data.losses, overtimelossrate= data.overtimeLosses/data.losses, goalpergame=data.goalsFor/data.gamesPlayed)

for (i in 1: nrow(new)){
  if (new$data.firstSeasonId[i]/10000<1943){
    new$age[i]<- "Senior"
  }
  else if (new$data.firstSeasonId[i]/10000<1968){
    new$age[i]<- "Junior"
  }
  else if (new$data.firstSeasonId[i]/10000<1993){
    new$age[i]<- "Sophomore"
  }
  else {
    new$age[i]<- "Freshman"
  }
}

```

```{r contingency table}

levels(new$age)<-list("1917-1942"="Freshman","1942-1967"="Sophomore","1967-1992"="Junior","1992-2017"="Senior")
table1 <- table(new$teams.division.name,new$age)
table1 

```

```{r histogram}
type2 <- new %>% filter(data.gameTypeId==2)
type3 <- new %>% filter(data.gameTypeId==3)
histo1 <- ggplot(data=type2,aes(x=data.penaltyMinutes))
histo1+geom_histogram(binwidth = 10000)

histo2 <- ggplot(data=type3,aes(x=data.penaltyMinutes))
histo2+geom_histogram(binwidth = 800)
```

```{r summary}

calculate <- function(x,...){
  data <- new %>% filter(data.gameTypeId == x)%>% select(winrate,winlossrate,overtimelossrate,goalpergame)
    kable(apply(data,2, summary), digit = 4,caption = paste0("Summary of gametpye", x))
}
calculate(2)
calculate(3)
 #if(x==2) caption="summary of regular season" else caption="summary of playoff season"
#caption = paste0("Summary of gametpyre", x)

```

#render("Project1.Rmd", output_format ="github_document", output_file=I("README.md"))